# https://medium.com/@itsuki.enjoy/dockerize-a-next-js-app-4b03021e084d
version: "3.8"
services:
  app:
    build:
      context: ./
      # target: dev
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
